#IMPORTING AND MERGING DATA

setwd("/home/usuario/Documentos/UNED/TFM/Outlier Blindness/DATA_OUTLIER_BLINDNESS_PAPER/DATA_hue_task_5trial_adaptation")

datap1_01<-read.csv(file("guest1.csv"),nrows=1000,header=T,sep=",")
datap1_02<-read.csv(file("guest2.csv"),nrows=1000,header=T,sep=",")
datap1_03<-read.csv(file("guest3.csv"),nrows=1000,header=T,sep=",")
datap1_04<-read.csv(file("guest4.csv"),nrows=1000,header=T,sep=",")
datap1_05<-read.csv(file("guest5.csv"),nrows=1000,header=T,sep=",")
datap1_06<-read.csv(file("guest6.csv"),nrows=1000,header=T,sep=",") 
datap1_07<-read.csv(file("guest7.csv"),nrows=1000,header=T,sep=",")
datap1_08<-read.csv(file("guest8.csv"),nrows=1000,header=T,sep=",")
datap1_09<-read.csv(file("guest9.csv"),nrows=1000,header=T,sep=",")
datap1_10<-read.csv(file("guest10.csv"),nrows=1000,header=T,sep=",")
datap1_11<-read.csv(file("guest11.csv"),nrows=1000,header=T,sep=",")
datap1_12<-read.csv(file("guest12.csv"),nrows=1000,header=T,sep=",")
datap1_13<-read.csv(file("guest13.csv"),nrows=1000,header=T,sep=",")
datap1_14<-read.csv(file("guest14.csv"),nrows=1000,header=T,sep=",")
datap1_15<-read.csv(file("guest15.csv"),nrows=1000,header=T,sep=",")
datap1_16<-read.csv(file("guest16.csv"),nrows=1000,header=T,sep=",")
datap1_17<-read.csv(file("guest17.csv"),nrows=1000,header=T,sep=",")
datap1_18<-read.csv(file("guest18.csv"),nrows=1000,header=T,sep=",")
datap1_19<-read.csv(file("guest19.csv"),nrows=1000,header=T,sep=",")
datap1_20<-read.csv(file("guest20.csv"),nrows=1000,header=T,sep=",")
datap1_21<-read.csv(file("guest21.csv"),nrows=1000,header=T,sep=",")
datap1_22<-read.csv(file("guest22.csv"),nrows=1000,header=T,sep=",")
datap1_23<-read.csv(file("guest23.csv"),nrows=1000,header=T,sep=",")
datap1_24<-read.csv(file("guest24.csv"),nrows=1000,header=T,sep=",")
datap1_25<-read.csv(file("guest25.csv"),nrows=1000,header=T,sep=",")
datap1_26<-read.csv(file("guest26.csv"),nrows=1000,header=T,sep=",")
datap1_27<-read.csv(file("guest27.csv"),nrows=1000,header=T,sep=",")
datap1_28<-read.csv(file("guest28.csv"),nrows=1000,header=T,sep=",")
datap1_29<-read.csv(file("guest29.csv"),nrows=1000,header=T,sep=",")
datap1_30<-read.csv(file("guest30.csv"),nrows=1000,header=T,sep=",")
datap1_31<-read.csv(file("guest31.csv"),nrows=1000,header=T,sep=",")

setwd("/home/usuario/Documentos/UNED/TFM/Outlier Blindness/DATA_OUTLIER_BLINDNESS_PAPER/DATA_hue_task_placebo")

datap2_01<-read.csv(file("guest1.csv"),nrows=960,header=T,sep=",")
datap2_02<-read.csv(file("guest2.csv"),nrows=960,header=T,sep=",")
datap2_03<-read.csv(file("guest3.csv"),nrows=960,header=T,sep=",")
datap2_04<-read.csv(file("guest4.csv"),nrows=960,header=T,sep=",")
datap2_05<-read.csv(file("guest5.csv"),nrows=960,header=T,sep=",")
datap2_06<-read.csv(file("guest6.csv"),nrows=960,header=T,sep=",") 
datap2_07<-read.csv(file("guest7.csv"),nrows=960,header=T,sep=",")
datap2_08<-read.csv(file("guest8.csv"),nrows=960,header=T,sep=",")
datap2_09<-read.csv(file("guest9.csv"),nrows=960,header=T,sep=",")
datap2_10<-read.csv(file("guest10.csv"),nrows=960,header=T,sep=",")
datap2_11<-read.csv(file("guest11.csv"),nrows=960,header=T,sep=",")
datap2_12<-read.csv(file("guest12.csv"),nrows=960,header=T,sep=",")
datap2_13<-read.csv(file("guest13.csv"),nrows=960,header=T,sep=",")
datap2_14<-read.csv(file("guest14.csv"),nrows=960,header=T,sep=",")
datap2_15<-read.csv(file("guest15.csv"),nrows=960,header=T,sep=",")
datap2_16<-read.csv(file("guest16.csv"),nrows=960,header=T,sep=",")
datap2_17<-read.csv(file("guest17.csv"),nrows=960,header=T,sep=",")
datap2_18<-read.csv(file("guest18.csv"),nrows=960,header=T,sep=",")
datap2_19<-read.csv(file("guest19.csv"),nrows=960,header=T,sep=",")
datap2_20<-read.csv(file("guest20.csv"),nrows=960,header=T,sep=",")
datap2_21<-read.csv(file("guest21.csv"),nrows=960,header=T,sep=",")
datap2_22<-read.csv(file("guest22.csv"),nrows=960,header=T,sep=",")#
datap2_23<-read.csv(file("guest23.csv"),nrows=960,header=T,sep=",")
datap2_24<-read.csv(file("guest24.csv"),nrows=960,header=T,sep=",")
datap2_25<-read.csv(file("guest25.csv"),nrows=960,header=T,sep=",")
datap2_26<-read.csv(file("guest26.csv"),nrows=960,header=T,sep=",")
datap2_27<-read.csv(file("guest27.csv"),nrows=960,header=T,sep=",")
datap2_28<-read.csv(file("guest28.csv"),nrows=960,header=T,sep=",")
datap2_29<-read.csv(file("guest29.csv"),nrows=960,header=T,sep=",")
datap2_30<-read.csv(file("guest30.csv"),nrows=960,header=T,sep=",")
datap2_31<-read.csv(file("guest31.csv"),nrows=960,header=T,sep=",")
datap2_32<-read.csv(file("guest32.csv"),nrows=960,header=T,sep=",")
datap2_33<-read.csv(file("guest33.csv"),nrows=960,header=T,sep=",")
datap2_34<-read.csv(file("guest34.csv"),nrows=960,header=T,sep=",")
datap2_35<-read.csv(file("guest35.csv"),nrows=960,header=T,sep=",")

setwd("/home/usuario/Documentos/UNED/TFM/Outlier Blindness/DATA_OUTLIER_BLINDNESS_PAPER/DATA_huetask_main_exepriment_session1")

datas1_01<-read.csv(file("guest1.csv"),nrows=1248,header=T,sep=",")
datas1_02<-read.csv(file("guest2.csv"),nrows=1248,header=T,sep=",")
datas1_03<-read.csv(file("guest3.csv"),nrows=1128,header=T,sep=",")
datas1_04<-read.csv(file("guest4.csv"),nrows=1128,header=T,sep=",")
datas1_05<-read.csv(file("guest5.csv"),nrows=1128,header=T,sep=",")
datas1_06<-read.csv(file("guest6.csv"),nrows=1128,header=T,sep=",") 
datas1_07<-read.csv(file("guest7.csv"),nrows=1128,header=T,sep=",")
datas1_08<-read.csv(file("guest8.csv"),nrows=1128,header=T,sep=",")
datas1_09<-read.csv(file("guest9.csv"),nrows=1128,header=T,sep=",")
datas1_10<-read.csv(file("guest10.csv"),nrows=1128,header=T,sep=",")
datas1_11<-read.csv(file("guest11.csv"),nrows=1128,header=T,sep=",")
datas1_12<-read.csv(file("guest12.csv"),nrows=1128,header=T,sep=",")
datas1_13<-read.csv(file("guest13.csv"),nrows=1128,header=T,sep=",")
datas1_14<-read.csv(file("guest14.csv"),nrows=1128,header=T,sep=",")
datas1_15<-read.csv(file("guest15.csv"),nrows=1128,header=T,sep=",")
datas1_16<-read.csv(file("guest16.csv"),nrows=1128,header=T,sep=",")
datas1_17<-read.csv(file("guest17.csv"),nrows=1128,header=T,sep=",")
datas1_18<-read.csv(file("guest18.csv"),nrows=1128,header=T,sep=",")
datas1_19<-read.csv(file("guest19.csv"),nrows=1128,header=T,sep=",")
datas1_21<-read.csv(file("guest21.csv"),nrows=1128,header=T,sep=",")
datas1_22<-read.csv(file("guest22.csv"),nrows=1128,header=T,sep=",")
datas1_23<-read.csv(file("guest23.csv"),nrows=1128,header=T,sep=",")
datas1_24<-read.csv(file("guest24.csv"),nrows=1128,header=T,sep=",")
datas1_25<-read.csv(file("guest25.csv"),nrows=1128,header=T,sep=",")
datas1_26<-read.csv(file("guest26.csv"),nrows=1128,header=T,sep=",")
datas1_27<-read.csv(file("guest27.csv"),nrows=1128,header=T,sep=",")
datas1_28<-read.csv(file("guest28.csv"),nrows=1128,header=T,sep=",")
datas1_29<-read.csv(file("guest29.csv"),nrows=1128,header=T,sep=",")
datas1_30<-read.csv(file("guest30.csv"),nrows=1128,header=T,sep=",")
datas1_31<-read.csv(file("guest31.csv"),nrows=1128,header=T,sep=",")

setwd("/home/usuario/Documentos/UNED/TFM/Outlier Blindness/DATA_OUTLIER_BLINDNESS_PAPER/DATA_huetask_main_experiment_session2")

datas2_01<-read.csv(file("guest1.csv"),nrows=1128,header=T,sep=",")
datas2_02<-read.csv(file("guest2.csv"),nrows=1128,header=T,sep=",")
datas2_03<-read.csv(file("guest3.csv"),nrows=1128,header=T,sep=",")
datas2_04<-read.csv(file("guest4.csv"),nrows=1128,header=T,sep=",")
datas2_05<-read.csv(file("guest5.csv"),nrows=1128,header=T,sep=",")
datas2_06<-read.csv(file("guest6.csv"),nrows=1128,header=T,sep=",") 
datas2_07<-read.csv(file("guest7.csv"),nrows=1128,header=T,sep=",")
datas2_08<-read.csv(file("guest8.csv"),nrows=1128,header=T,sep=",")
datas2_09<-read.csv(file("guest9.csv"),nrows=1128,header=T,sep=",")
datas2_10<-read.csv(file("guest10.csv"),nrows=1128,header=T,sep=",")
datas2_11<-read.csv(file("guest11.csv"),nrows=1128,header=T,sep=",")
datas2_12<-read.csv(file("guest12.csv"),nrows=1128,header=T,sep=",")
datas2_13<-read.csv(file("guest13.csv"),nrows=1128,header=T,sep=",")
datas2_14<-read.csv(file("guest14.csv"),nrows=1128,header=T,sep=",")
datas2_15<-read.csv(file("guest15.csv"),nrows=1128,header=T,sep=",")
datas2_16<-read.csv(file("guest16.csv"),nrows=1128,header=T,sep=",")
datas2_17<-read.csv(file("guest17.csv"),nrows=1128,header=T,sep=",")
datas2_18<-read.csv(file("guest18.csv"),nrows=1128,header=T,sep=",")
datas2_19<-read.csv(file("guest19.csv"),nrows=1128,header=T,sep=",")
datas2_20<-read.csv(file("guest20.csv"),nrows=1128,header=T,sep=",")
datas2_21<-read.csv(file("guest21.csv"),nrows=1128,header=T,sep=",")
datas2_22<-read.csv(file("guest22.csv"),nrows=1128,header=T,sep=",")
datas2_23<-read.csv(file("guest23.csv"),nrows=1128,header=T,sep=",")
datas2_24<-read.csv(file("guest24.csv"),nrows=1128,header=T,sep=",")
datas2_25<-read.csv(file("guest25.csv"),nrows=1128,header=T,sep=",")
datas2_26<-read.csv(file("guest26.csv"),nrows=1128,header=T,sep=",")
datas2_27<-read.csv(file("guest27.csv"),nrows=1128,header=T,sep=",")
datas2_28<-read.csv(file("guest28.csv"),nrows=1128,header=T,sep=",")
datas2_29<-read.csv(file("guest29.csv"),nrows=1128,header=T,sep=",")
datas2_30<-read.csv(file("guest30.csv"),nrows=1128,header=T,sep=",")
datas2_31<-read.csv(file("guest31.csv"),nrows=1128,header=T,sep=",")
datas2_32<-read.csv(file("guest32.csv"),nrows=1128,header=T,sep=",")
datas2_33<-read.csv(file("guest33.csv"),nrows=1128,header=T,sep=",")

setwd("/home/usuario/Documentos/UNED/TFM/Outlier Blindness/DATA_OUTLIER_BLINDNESS_PAPER/DATA_huetask_double_response_time")

datas3_01<-read.csv(file("guest1.csv"),nrows=1128,header=T,sep=",")
datas3_02<-read.csv(file("guest2.csv"),nrows=1128,header=T,sep=",")
datas3_03<-read.csv(file("guest3.csv"),nrows=1128,header=T,sep=",")
datas3_04<-read.csv(file("guest4.csv"),nrows=1128,header=T,sep=",")
datas3_05<-read.csv(file("guest5.csv"),nrows=1128,header=T,sep=",")
datas3_06<-read.csv(file("guest6.csv"),nrows=1128,header=T,sep=",") 
datas3_07<-read.csv(file("guest7.csv"),nrows=1128,header=T,sep=",")
datas3_08<-read.csv(file("guest8.csv"),nrows=1128,header=T,sep=",")
datas3_09<-read.csv(file("guest9.csv"),nrows=1128,header=T,sep=",")
datas3_10<-read.csv(file("guest10.csv"),nrows=1128,header=T,sep=",")
datas3_11<-read.csv(file("guest11.csv"),nrows=1128,header=T,sep=",")
datas3_12<-read.csv(file("guest12.csv"),nrows=1128,header=T,sep=",")
datas3_13<-read.csv(file("guest13.csv"),nrows=1128,header=T,sep=",")
datas3_14<-read.csv(file("guest14.csv"),nrows=1128,header=T,sep=",")
datas3_15<-read.csv(file("guest15.csv"),nrows=1128,header=T,sep=",")
datas3_16<-read.csv(file("guest16.csv"),nrows=1128,header=T,sep=",")
datas3_17<-read.csv(file("guest17.csv"),nrows=1128,header=T,sep=",")
datas3_18<-read.csv(file("guest18.csv"),nrows=1128,header=T,sep=",")
datas3_19<-read.csv(file("guest19.csv"),nrows=112,header=T,sep=",")
datas3_20<-read.csv(file("guest20.csv"),nrows=1128,header=T,sep=",")
datas3_21<-read.csv(file("guest21.csv"),nrows=1128,header=T,sep=",")
datas3_22<-read.csv(file("guest22.csv"),nrows=1128,header=T,sep=",")
datas3_23<-read.csv(file("guest23.csv"),nrows=1128,header=T,sep=",")
datas3_24<-read.csv(file("guest24.csv"),nrows=1128,header=T,sep=",")
datas3_25<-read.csv(file("guest25.csv"),nrows=1128,header=T,sep=",")
datas3_26<-read.csv(file("guest26.csv"),nrows=1128,header=T,sep=",")
datas3_27<-read.csv(file("guest27.csv"),nrows=1128,header=T,sep=",")
datas3_28<-read.csv(file("guest28.csv"),nrows=1128,header=T,sep=",")
datas3_29<-read.csv(file("guest29.csv"),nrows=1128,header=T,sep=",")
datas3_30<-read.csv(file("guest30.csv"),nrows=1128,header=T,sep=",")
datas3_31<-read.csv(file("guest31.csv"),nrows=1128,header=T,sep=",")
datas3_32<-read.csv(file("guest32.csv"),nrows=1128,header=T,sep=",")
datas3_33<-read.csv(file("guest33.csv"),nrows=1128,header=T,sep=",")

user<-c("p1_01")
session<-c("p1")
datap1_01<-cbind(datap1_01,user,session)
user<-c("p1_02")
datap1_02<-cbind(datap1_02,user,session)
user<-c("p1_03")
datap1_03<-cbind(datap1_03,user,session)
user<-c("p1_04")
datap1_04<-cbind(datap1_04,user,session)
user<-c("p1_05")
datap1_05<-cbind(datap1_05,user,session)
user<-c("p1_06")
datap1_06<-cbind(datap1_06,user,session)
user<-c("p1_07")
datap1_07<-cbind(datap1_07,user,session)
user<-c("p1_08")
datap1_08<-cbind(datap1_08,user,session)
user<-c("p1_09")
datap1_09<-cbind(datap1_09,user,session)
user<-c("p1_10")
datap1_10<-cbind(datap1_10,user,session)
user<-c("p1_11")
datap1_11<-cbind(datap1_11,user,session)
user<-c("p1_12")
datap1_12<-cbind(datap1_12,user,session)
user<-c("p1_13")
datap1_13<-cbind(datap1_13,user,session)
user<-c("p1_14")
datap1_14<-cbind(datap1_14,user,session)
user<-c("p1_15")
datap1_15<-cbind(datap1_15,user,session)
user<-c("p1_16")
datap1_16<-cbind(datap1_16,user,session)
user<-c("p1_17")
datap1_17<-cbind(datap1_17,user,session)
user<-c("p1_18")
datap1_18<-cbind(datap1_18,user,session)
user<-c("p1_19")
datap1_19<-cbind(datap1_19,user,session)
user<-c("p1_20")
datap1_20<-cbind(datap1_20,user,session)
user<-c("p1_21")
datap1_21<-cbind(datap1_21,user,session)
user<-c("p1_22")
datap1_22<-cbind(datap1_22,user,session)
user<-c("p1_23")
datap1_23<-cbind(datap1_23,user,session)
user<-c("p1_24")
datap1_24<-cbind(datap1_24,user,session)
user<-c("p1_25")
datap1_25<-cbind(datap1_25,user,session)
user<-c("p1_26")
datap1_26<-cbind(datap1_26,user,session)
user<-c("p1_27")
datap1_27<-cbind(datap1_27,user,session)
user<-c("p1_28")
datap1_28<-cbind(datap1_28,user,session)
user<-c("p1_29")
datap1_29<-cbind(datap1_29,user,session)
user<-c("p1_30")
datap1_30<-cbind(datap1_30,user,session)
user<-c("p1_31")
datap1_31<-cbind(datap1_31,user,session)

user<-c("p2_01")
session<-c("p2")
datap2_01<-cbind(datap2_01,user,session)
user<-c("p2_02")
datap2_02<-cbind(datap2_02,user,session)
user<-c("p2_03")
datap2_03<-cbind(datap2_03,user,session)
user<-c("p2_04")
datap2_04<-cbind(datap2_04,user,session)
user<-c("p2_05")
datap2_05<-cbind(datap2_05,user,session)
user<-c("p2_06")
datap2_06<-cbind(datap2_06,user,session)
user<-c("p2_07")
datap2_07<-cbind(datap2_07,user,session)
user<-c("p2_08")
datap2_08<-cbind(datap2_08,user,session)
user<-c("p2_09")
datap2_09<-cbind(datap2_09,user,session)
user<-c("p2_10")
datap2_10<-cbind(datap2_10,user,session)
user<-c("p2_11")
datap2_11<-cbind(datap2_11,user,session)
user<-c("p2_12")
datap2_12<-cbind(datap2_12,user,session)
user<-c("p2_13")
datap2_13<-cbind(datap2_13,user,session)
user<-c("p2_14")
datap2_14<-cbind(datap2_14,user,session)
user<-c("p2_15")
datap2_15<-cbind(datap2_15,user,session)
user<-c("p2_16")
datap2_16<-cbind(datap2_16,user,session)
user<-c("p2_17")
datap2_17<-cbind(datap2_17,user,session)
user<-c("p2_18")
datap2_18<-cbind(datap2_18,user,session)
user<-c("p2_19")
datap2_19<-cbind(datap2_19,user,session)
user<-c("p2_20")
datap2_20<-cbind(datap2_20,user,session)
user<-c("p2_21")
datap2_21<-cbind(datap2_21,user,session)
user<-c("p2_22")
datap2_22<-cbind(datap2_22,user,session)
user<-c("p2_23")
datap2_23<-cbind(datap2_23,user,session)
user<-c("p2_24")
datap2_24<-cbind(datap2_24,user,session)
user<-c("p2_25")
datap2_25<-cbind(datap2_25,user,session)
user<-c("p2_26")
datap2_26<-cbind(datap2_26,user,session)
user<-c("p2_27")
datap2_27<-cbind(datap2_27,user,session)
user<-c("p2_28")
datap2_28<-cbind(datap2_28,user,session)
user<-c("p2_29")
datap2_29<-cbind(datap2_29,user,session)
user<-c("p2_30")
datap2_30<-cbind(datap2_30,user,session)
user<-c("p2_31")
datap2_31<-cbind(datap2_31,user,session)
user<-c("p2_32")
datap2_32<-cbind(datap2_32,user,session)
user<-c("p2_33")
datap2_33<-cbind(datap2_33,user,session)
user<-c("p2_34")
datap2_34<-cbind(datap2_34,user,session)
user<-c("p2_35")
datap2_35<-cbind(datap2_35,user,session)

user<-c("s1_01")
session<-c("s1s2")
datas1_01<-cbind(datas1_01,user,session)
user<-c("s1_02")
datas1_02<-cbind(datas1_02,user,session)
user<-c("s1_03")
datas1_03<-cbind(datas1_03,user,session)
user<-c("s1_04")
datas1_04<-cbind(datas1_04,user,session)
user<-c("s1_05")
datas1_05<-cbind(datas1_05,user,session)
user<-c("s1_06")
datas1_06<-cbind(datas1_06,user,session)
user<-c("s1_07")
datas1_07<-cbind(datas1_07,user,session)
user<-c("s1_08")
datas1_08<-cbind(datas1_08,user,session)
user<-c("s1_09")
datas1_09<-cbind(datas1_09,user,session)
user<-c("s1_10")
datas1_10<-cbind(datas1_10,user,session)
user<-c("s1_11")
datas1_11<-cbind(datas1_11,user,session)
user<-c("s1_12")
datas1_12<-cbind(datas1_12,user,session)
user<-c("s1_13")
datas1_13<-cbind(datas1_13,user,session)
user<-c("s1_14")
datas1_14<-cbind(datas1_14,user,session)
user<-c("s1_15")
datas1_15<-cbind(datas1_15,user,session)
user<-c("s1_16")
datas1_16<-cbind(datas1_16,user,session)
user<-c("s1_17")
datas1_17<-cbind(datas1_17,user,session)
user<-c("s1_18")
datas1_18<-cbind(datas1_18,user,session)
user<-c("s1_19")
datas1_19<-cbind(datas1_19,user,session)
user<-c("s1_21")
datas1_21<-cbind(datas1_21,user,session)
user<-c("s1_22")
datas1_22<-cbind(datas1_22,user,session)
user<-c("s1_23")
datas1_23<-cbind(datas1_23,user,session)
user<-c("s1_24")
datas1_24<-cbind(datas1_24,user,session)
user<-c("s1_25")
datas1_25<-cbind(datas1_25,user,session)
user<-c("s1_26")
datas1_26<-cbind(datas1_26,user,session)
user<-c("s1_27")
datas1_27<-cbind(datas1_27,user,session)
user<-c("s1_28")
datas1_28<-cbind(datas1_28,user,session)
user<-c("s1_29")
datas1_29<-cbind(datas1_29,user,session)
user<-c("s1_30")
datas1_30<-cbind(datas1_30,user,session)
user<-c("s1_31")
datas1_31<-cbind(datas1_31,user,session)

user<-c("s2_01")
session<-c("s1s2")
datas2_01<-cbind(datas2_01,user,session)
user<-c("s2_02")
datas2_02<-cbind(datas2_02,user,session)
user<-c("s2_03")
datas2_03<-cbind(datas2_03,user,session)
user<-c("s2_04")
datas2_04<-cbind(datas2_04,user,session)
user<-c("s2_05")
datas2_05<-cbind(datas2_05,user,session)
user<-c("s2_06")
datas2_06<-cbind(datas2_06,user,session)
user<-c("s2_07")
datas2_07<-cbind(datas2_07,user,session)
user<-c("s2_08")
datas2_08<-cbind(datas2_08,user,session)
user<-c("s2_09")
datas2_09<-cbind(datas2_09,user,session)
user<-c("s2_10")
datas2_10<-cbind(datas2_10,user,session)
user<-c("s2_11")
datas2_11<-cbind(datas2_11,user,session)
user<-c("s2_12")
datas2_12<-cbind(datas2_12,user,session)
user<-c("s2_13")
datas2_13<-cbind(datas2_13,user,session)
user<-c("s2_14")
datas2_14<-cbind(datas2_14,user,session)
user<-c("s2_15")
datas2_15<-cbind(datas2_15,user,session)
user<-c("s2_16")
datas2_16<-cbind(datas2_16,user,session)
user<-c("s2_17")
datas2_17<-cbind(datas2_17,user,session)
user<-c("s2_18")
datas2_18<-cbind(datas2_18,user,session)
user<-c("s2_19")
datas2_19<-cbind(datas2_19,user,session)
user<-c("s2_20")
datas2_20<-cbind(datas2_20,user,session)
user<-c("s2_21")
datas2_21<-cbind(datas2_21,user,session)
user<-c("s2_22")
datas2_22<-cbind(datas2_22,user,session)
user<-c("s2_23")
datas2_23<-cbind(datas2_23,user,session)
user<-c("s2_24")
datas2_24<-cbind(datas2_24,user,session)
user<-c("s2_25")
datas2_25<-cbind(datas2_25,user,session)
user<-c("s2_26")
datas2_26<-cbind(datas2_26,user,session)
user<-c("s2_27")
datas2_27<-cbind(datas2_27,user,session)
user<-c("s2_28")
datas2_28<-cbind(datas2_28,user,session)
user<-c("s2_29")
datas2_29<-cbind(datas2_29,user,session)
user<-c("s2_30")
datas2_30<-cbind(datas2_30,user,session)
user<-c("s2_31")
datas2_31<-cbind(datas2_31,user,session)
user<-c("s2_32")
datas2_32<-cbind(datas2_32,user,session)
user<-c("s2_33")
datas2_33<-cbind(datas2_33,user,session)

user<-c("s3_01")
session<-c("s3")
datas3_01<-cbind(datas3_01,user,session)
user<-c("s3_02")
datas3_02<-cbind(datas3_02,user,session)
user<-c("s3_03")
datas3_03<-cbind(datas3_03,user,session)
user<-c("s3_04")
datas3_04<-cbind(datas3_04,user,session)
user<-c("s3_05")
datas3_05<-cbind(datas3_05,user,session)
user<-c("s3_06")
datas3_06<-cbind(datas3_06,user,session)
user<-c("s3_07")
datas3_07<-cbind(datas3_07,user,session)
user<-c("s3_08")
datas3_08<-cbind(datas3_08,user,session)
user<-c("s3_09")
datas3_09<-cbind(datas3_09,user,session)
user<-c("s3_10")
datas3_10<-cbind(datas3_10,user,session)
user<-c("s3_11")
datas3_11<-cbind(datas3_11,user,session)
user<-c("s3_12")
datas3_12<-cbind(datas3_12,user,session)
user<-c("s3_13")
datas3_13<-cbind(datas3_13,user,session)
user<-c("s3_14")
datas3_14<-cbind(datas3_14,user,session)
user<-c("s3_15")
datas3_15<-cbind(datas3_15,user,session)
user<-c("s3_16")
datas3_16<-cbind(datas3_16,user,session)
user<-c("s3_17")
datas3_17<-cbind(datas3_17,user,session)
user<-c("s3_18")
datas3_18<-cbind(datas3_18,user,session)
user<-c("s3_19")
datas3_19<-cbind(datas3_19,user,session)
user<-c("s3_20")
datas3_20<-cbind(datas3_20,user,session)
user<-c("s3_21")
datas3_21<-cbind(datas3_21,user,session)
user<-c("s3_22")
datas3_22<-cbind(datas3_22,user,session)
user<-c("s3_23")
datas3_23<-cbind(datas3_23,user,session)
user<-c("s3_24")
datas3_24<-cbind(datas3_24,user,session)
user<-c("s3_25")
datas3_25<-cbind(datas3_25,user,session)
user<-c("s3_26")
datas3_26<-cbind(datas3_26,user,session)
user<-c("s3_27")
datas3_27<-cbind(datas3_27,user,session)
user<-c("s3_28")
datas3_28<-cbind(datas3_28,user,session)
user<-c("s3_29")
datas3_29<-cbind(datas3_29,user,session)
user<-c("s3_30")
datas3_30<-cbind(datas3_30,user,session)
user<-c("s3_31")
datas3_31<-cbind(datas3_31,user,session)
user<-c("s3_32")
datas3_32<-cbind(datas3_32,user,session)
user<-c("s3_33")
datas3_33<-cbind(datas3_33,user,session)

datap1<-rbind(datap1_01,datap1_02,datap1_03,datap1_04,datap1_05,datap1_06,datap1_07,datap1_08,datap1_09,datap1_10,datap1_11,datap1_12,datap1_13,datap1_14,datap1_15,datap1_16,datap1_17,datap1_18,datap1_19,datap1_20,datap1_21,datap1_22,datap1_23,datap1_24,datap1_25,datap1_26,datap1_27,datap1_28,datap1_29,datap1_30,datap1_31)

datap2<-rbind(datap2_01,datap2_02,datap2_03,datap2_04,datap2_05,datap2_06,datap2_07,datap2_08,datap2_09,datap2_10,datap2_11,datap2_12,datap2_13,datap2_14,datap2_15,datap2_16,datap2_17,datap2_18,datap2_19,datap2_20,datap2_21,datap2_22,datap2_23,datap2_24,datap2_25,datap2_26,datap2_27,datap2_28,datap2_29,datap2_30,datap2_31,datap2_32,datap2_33,datap2_34,datap2_35)

datas1<-rbind(datas1_01,datas1_02,datas1_03,datas1_04,datas1_05,datas1_06,datas1_07,datas1_08,datas1_09,datas1_10,datas1_11,datas1_12,datas1_13,datas1_14,datas1_15,datas1_16,datas1_17,datas1_18,datas1_19,datas1_21,datas1_22,datas1_23,datas1_24,datas1_25,datas1_26,datas1_27,datas1_28,datas1_29,datas1_30,datas1_31)

datas2<-rbind(datas2_01,datas2_02,datas2_03,datas2_04,datas2_05,datas2_06,datas2_07,datas2_08,datas2_09,datas2_10,datas2_11,datas2_12,datas2_13,datas2_14,datas2_15,datas2_16,datas2_17,datas2_18,datas2_19,datas2_20,datas2_21,datas2_22,datas2_23,datas2_24,datas2_25,datas2_26,datas2_27,datas2_28,datas2_29,datas2_30,datas2_31,datas2_32,datas2_33)

datas3<-rbind(datas3_01,datas3_02,datas3_03,datas3_04,datas3_05,datas3_06,datas3_07,datas3_08,datas3_09,datas3_10,datas3_11,datas3_12,datas3_13,datas3_14,datas3_15,datas3_16,datas3_17,datas3_18,datas3_19,datas3_20,datas3_21,datas3_22,datas3_23,datas3_24,datas3_25,datas3_26,datas3_27,datas3_28,datas3_29,datas3_30,datas3_31,datas3_32,datas3_33)

data<-rbind(datap1,datap2,datas1,datas2,datas3)

#ACCURACY SUMMARY STATISTICS

correct<-ifelse(data$Resp==1,1,0)
trialtype<-ifelse(grepl("Adpative_Trial",data$Trial.Type.mean.std), "adaptivetrial",ifelse(grepl("Adpative_Same_Color_Trial",data$Trial.Type.mean.std), "adaptivetrial",ifelse(grepl("Control_Trial",data$Trial.Type.mean.std), "controltrial",ifelse(grepl("Control_Same_Color_Trial",data$Trial.Type.mean.std), "controltrial",ifelse(grepl("Adpative_Test",data$Trial.Type.mean.std), "adaptivetest","controltest")))))
samecolor<-ifelse(grepl("Same_Color",data$Trial.Type.mean.std),1,0)
data<-cbind(data,correct,trialtype,samecolor)

data_adaptivetrial<-subset(data,trialtype=="adaptivetrial")
data_controltrial<-subset(data,trialtype=="controltrial")
data_adaptivetest<-subset(data,trialtype=="adaptivetest")
data_controltest<-subset(data,trialtype=="controltest")
data_samecolor<-subset(data,samecolor==1)
data_diffcolor<-subset(data,samecolor==0)

accuracy_overall<-setNames(aggregate(data$correct, by=list(data$user),FUN=mean),c("user","accuracy_overall"))

accuracy_samecolor<-setNames(aggregate(data_samecolor$correct, by=list(data_samecolor$user),FUN=mean),c("user","accuracy_samecolor"))

accuracy_diffcolor<-setNames(aggregate(data_diffcolor$correct, by=list(data_diffcolor$user),FUN=mean),c("user","accuracy_diffcolor"))

accuracy_adaptivetrial<-setNames(aggregate(data_adaptivetrial$correct, by=list(data_adaptivetrial$user),FUN=mean),c("user","accuracy_adaptivetrial"))

accuracy_controltrial<-setNames(aggregate(data_controltrial$correct,
                                          by=list(data_controltrial$user),FUN=mean),c("user","accuracy_controltrial"))

accuracy_adaptivetest<-setNames(aggregate(data_adaptivetest$correct, by=list(data_adaptivetest$user),FUN=mean),c("user","accuracy_adaptivetest"))

accuracy_controltest<-setNames(aggregate(data_controltest$correct, by=list(data_controltest$user),FUN=mean),c("user","accuracy_controltest"))

accuracydata<-merge(accuracy_overall,accuracy_samecolor)
accuracydata<-merge(accuracydata,accuracy_diffcolor)
accuracydata<-merge(accuracydata,accuracy_adaptivetrial)
accuracydata<-merge(accuracydata,accuracy_controltrial)
accuracydata<-merge(accuracydata,accuracy_adaptivetest)
accuracydata<-merge(accuracydata,accuracy_controltest)

session<-ifelse(grepl("s1",accuracydata$user),"s1s2",ifelse(grepl("s2",accuracydata$user),"s1s2",ifelse(grepl("s3",accuracydata$user),"s3",ifelse(grepl("p1",accuracydata$user),"p1",ifelse(grepl("p2",accuracydata$user),"p2",0)))))

accuracydata<-cbind(accuracydata,session)
accuracydata<-accuracydata[, c(1, 9, 2, 3, 4, 5, 6, 7, 8)]

accuracy_overall_mean<-setNames(aggregate(accuracydata$accuracy_overall, by=list(accuracydata$session),FUN=mean),c("session","accuracy_overall_mean"))
se<-function(x) sd(x)/sqrt(length(x))
accuracy_overall_sd<-setNames(aggregate(accuracydata$accuracy_overall, by=list(accuracydata$session),FUN=sd),c("session","accuracy_overall_sd"))
accuracy_overall_se<-setNames(aggregate(accuracydata$accuracy_overall, by=list(accuracydata$session),FUN=se),c("session","accuracy_overall_se"))

accuracy_samecolor_mean<-setNames(aggregate(accuracydata$accuracy_samecolor, by=list(accuracydata$session),FUN=mean),c("session","accuracy_samecolor_mean"))
accuracy_samecolor_sd<-setNames(aggregate(accuracydata$accuracy_samecolor, by=list(accuracydata$session),FUN=sd),c("session","accuracy_samecolor_sd"))
accuracy_samecolor_se<-setNames(aggregate(accuracydata$accuracy_samecolor, by=list(accuracydata$session),FUN=se),c("session","accuracy_samecolor_se"))

accuracy_diffcolor_mean<-setNames(aggregate(accuracydata$accuracy_diffcolor, by=list(accuracydata$session),FUN=mean),c("session","accuracy_diffcolor_mean"))
accuracy_diffcolor_sd<-setNames(aggregate(accuracydata$accuracy_diffcolor, by=list(accuracydata$session),FUN=sd),c("session","accuracy_diffcolor_sd"))
accuracy_diffcolor_se<-setNames(aggregate(accuracydata$accuracy_diffcolor, by=list(accuracydata$session),FUN=se),c("session","accuracy_diffcolor_se"))

accuracy_adaptivetrial_mean<-setNames(aggregate(accuracydata$accuracy_adaptivetrial, by=list(accuracydata$session),FUN=mean),c("session","accuracy_adaptivetrial_mean"))
accuracy_adaptivetrial_sd<-setNames(aggregate(accuracydata$accuracy_adaptivetrial, by=list(accuracydata$session),FUN=sd),c("session","accuracy_adaptivetrial_sd"))
accuracy_adaptivetrial_se<-setNames(aggregate(accuracydata$accuracy_adaptivetrial, by=list(accuracydata$session),FUN=se),c("session","accuracy_adaptivetrial_se"))

accuracy_controltrial_mean<-setNames(aggregate(accuracydata$accuracy_controltrial, by=list(accuracydata$session),FUN=mean),c("session","accuracy_controltrial_mean"))
accuracy_controltrial_sd<-setNames(aggregate(accuracydata$accuracy_controltrial, by=list(accuracydata$session),FUN=sd),c("session","accuracy_controltrial_sd"))
accuracy_controltrial_se<-setNames(aggregate(accuracydata$accuracy_controltrial, by=list(accuracydata$session),FUN=se),c("session","accuracy_controltrial_se"))

accuracy_adaptivetest_mean<-setNames(aggregate(accuracydata$accuracy_adaptivetest, by=list(accuracydata$session),FUN=mean),c("session","accuracy_adaptivetest_mean"))
accuracy_adaptivetest_sd<-setNames(aggregate(accuracydata$accuracy_adaptivetest, by=list(accuracydata$session),FUN=sd),c("session","accuracy_adaptivetest_sd"))
accuracy_adaptivetest_se<-setNames(aggregate(accuracydata$accuracy_adaptivetest, by=list(accuracydata$session),FUN=se),c("session","accuracy_adaptivetest_se"))

accuracy_controltest_mean<-setNames(aggregate(accuracydata$accuracy_controltest, by=list(accuracydata$session),FUN=mean),c("session","accuracy_controltest_mean"))
accuracy_controltest_sd<-setNames(aggregate(accuracydata$accuracy_controltest, by=list(accuracydata$session),FUN=sd),c("session","accuracy_controltest_sd"))
accuracy_controltest_se<-setNames(aggregate(accuracydata$accuracy_controltest, by=list(accuracydata$session),FUN=se),c("session","accuracy_controltest_se"))

accuracybysession<-merge(accuracy_overall_mean,accuracy_overall_sd)
accuracybysession<-merge(accuracybysession,accuracy_overall_se)
accuracybysession<-merge(accuracybysession,accuracy_samecolor_mean)
accuracybysession<-merge(accuracybysession,accuracy_samecolor_sd)
accuracybysession<-merge(accuracybysession,accuracy_samecolor_se)
accuracybysession<-merge(accuracybysession,accuracy_diffcolor_mean)
accuracybysession<-merge(accuracybysession,accuracy_diffcolor_sd)
accuracybysession<-merge(accuracybysession,accuracy_diffcolor_se)
accuracybysession<-merge(accuracybysession,accuracy_adaptivetrial_mean)
accuracybysession<-merge(accuracybysession,accuracy_adaptivetrial_sd)
accuracybysession<-merge(accuracybysession,accuracy_adaptivetrial_se)
accuracybysession<-merge(accuracybysession,accuracy_controltrial_mean)
accuracybysession<-merge(accuracybysession,accuracy_controltrial_sd)
accuracybysession<-merge(accuracybysession,accuracy_controltrial_se)
accuracybysession<-merge(accuracybysession,accuracy_adaptivetest_mean)
accuracybysession<-merge(accuracybysession,accuracy_adaptivetest_sd)
accuracybysession<-merge(accuracybysession,accuracy_adaptivetest_se)
accuracybysession<-merge(accuracybysession,accuracy_controltest_mean)
accuracybysession<-merge(accuracybysession,accuracy_controltest_sd)
accuracybysession<-merge(accuracybysession,accuracy_controltest_se)

#ACCURACY PLOTS

library("reshape2")
library("ggsignif")
accuracydatamelt<-melt(accuracydata)
accuracydatamelt<-subset(accuracydatamelt,variable=="accuracy_adaptivetest"| variable=="accuracy_controltest")

accuracydatamelt_s1s2.p1.p2<-subset(accuracydatamelt,session=="s1s2"|session=="p1"|session=="p2")
sessionname<-
  ifelse(accuracydatamelt_s1s2.p1.p2$session=="p1","placebo1",
         ifelse(accuracydatamelt_s1s2.p1.p2$session=="p2","placebo2",
                ifelse(accuracydatamelt_s1s2.p1.p2$session=="s1s2","main.experiment",0)))
accuracydatamelt_s1s2.p1.p2<-cbind(accuracydatamelt_s1s2.p1.p2,sessionname)
library(ggplot2)
accuracydensityplot1<-ggplot(accuracydatamelt_s1s2.p1.p2) +geom_density(aes(x=value,colour=sessionname,linetype=variable),kernel="gaussian",adjust=4,show.legend=FALSE) +stat_density(aes(x=value,colour=sessionname,linetype=variable),geom="line",position="identity",size=0) +guides(colour=guide_legend(override.aes=list(size=1),title="Color"),linetype=guide_legend(override.aes=list(size=1),title="Line Type")) +xlab("Accuracy")+ylab("Density")+labs(title="Density Plot: \n Accuracy in Adaptive Test Trials and Control Test Trials \n for Main Experiment, 5-Trial Adaption Experiment, and Placebo Experiment") +theme_classic() +scale_linetype_manual(values=c("solid","dotted"),name="",breaks=c("accuracy_adaptivetest","accuracy_controltest"),labels=c("Accuracy in Adaptive Test Trials","Accuracy in Control Test Trials")) +scale_color_manual(values=c("blue","green","red"),name="",breaks=c("main.experiment","placebo1","placebo2"),labels=c("Main Experiment","5-Trial Adaption Experiment","Placebo Experiment")) +theme(plot.title=element_text(size=12),axis.title=element_text(size=12)) +scale_x_continuous(expand=c(0,0))+scale_y_continuous(expand=c(0,0),limit=c(0,5))

accuracydatamelt_s1s2.s3<-subset(accuracydatamelt,session=="s1s2"|session=="s3")
sessionname<-ifelse(accuracydatamelt_s1s2.s3$session=="s3","4.second.response.time",
                    ifelse(accuracydatamelt_s1s2.s3$session=="s1s2","2.second.response.time",0))
accuracydatamelt_s1s2.s3<-cbind(accuracydatamelt_s1s2.s3,sessionname)
accuracydensityplot2<-ggplot(accuracydatamelt_s1s2.s3) +geom_density(aes(x=value,colour=sessionname,linetype=variable),kernel="gaussian",adjust=4,show.legend=FALSE) +stat_density(aes(x=value,colour=sessionname,linetype=variable),geom="line",position="identity",size=0) +guides(colour=guide_legend(override.aes=list(size=1),title="Color"),linetype=guide_legend(override.aes=list(size=1),title="Line Type")) +xlab("Accuracy")+ylab("Density")+labs(title="Density Plot: \n Accuracy in Adaptive Test Trials and Control Test Trials \n According to Allotted Response Time") +theme_classic() +scale_linetype_manual(values=c("solid","dotted"),name="",breaks=c("accuracy_adaptivetest","accuracy_controltest"),labels=c("Accuracy in Adaptive Test Trials","Accuracy in Control Test Trials")) +scale_color_manual(values=c("blue","orange"),name="",breaks=c("2.second.response.time","4.second.response.time"),labels=c("Main Experiment","Double Response Time")) +theme(plot.title=element_text(size=12),axis.title=element_text(size=12)) +scale_x_continuous(expand=c(0,0))+scale_y_continuous(expand=c(0,0),limit=c(0,3.5))

accuracydatamelt_s1s2.p2<-subset(accuracydatamelt,session=="s1s2"| session=="p2")
sessionname<-
  ifelse(accuracydatamelt_s1s2.p2$session=="p2","placebo2",
         ifelse(accuracydatamelt_s1s2.p2$session=="s1s2","main.experiment",0))
accuracydatamelt_s1s2.p2<-cbind(accuracydatamelt_s1s2.p2,sessionname)
library(ggplot2)
accuracydensityplot3<-ggplot(accuracydatamelt_s1s2.p2) +geom_density(aes(x=value,colour=sessionname,linetype=variable),kernel="gaussian",adjust=4,show.legend=FALSE) +stat_density(aes(x=value,colour=sessionname,linetype=variable),geom="line",position="identity",size=0) +guides(colour=guide_legend(override.aes=list(size=1),title="Color"),linetype=guide_legend(override.aes=list(size=1),title="Line Type")) +xlab("Accuracy")+ylab("Density")+labs(title="Density Plot: \n Accuracy in Adaptive Test Trials and Control Test Trials \n for Main Experiment and Placebo Experiment") +theme_classic()+scale_linetype_manual(values=c("solid","dotted"),name="",breaks=c("accuracy_adaptivetest","accuracy_controltest"),labels=c("Accuracy in Adaptive Test Trials","Accuracy in Control Test Trials"))+scale_color_manual(values=c("blue","red"),name="",breaks=c("main.experiment","placebo2"),labels=c("Main Experiment","Placebo Experiment")) +theme(plot.title=element_text(size=12),axis.title=element_text(size=12)) +scale_x_continuous(expand=c(0,0))+scale_y_continuous(expand=c(0,0),limit=c(0,5))

accuracytestdata<-accuracydata[,c(1,2,8,9)]
ATDs1s2<-subset(accuracytestdata,session=="s1s2")
ATDs1s2<-melt(ATDs1s2)
Variable<-ifelse(ATDs1s2$variable=="accuracy_adaptivetest","Adaptive Test Trials",ifelse(ATDs1s2$variable=="accuracy_controltest","Control Test Trials",0))
ATDs1s2<-cbind(ATDs1s2,Variable)
ATDs1s2.summary<-data.frame(treatment=levels(ATDs1s2$Variable),mean=tapply(ATDs1s2$value,ATDs1s2$Variable,mean),n=tapply(ATDs1s2$value,ATDs1s2$Variable,length),sd=tapply(ATDs1s2$value,ATDs1s2$Variable,sd))
ATDs1s2.summary$se<-ATDs1s2.summary$sd/sqrt(ATDs1s2.summary$n)
mainexperimentaccuracybar<-ggplot(ATDs1s2.summary,aes(x=treatment,y=mean)) +geom_bar(position=position_dodge(),stat="identity",fill="skyblue",width=0.4) +geom_errorbar(aes(ymin=mean-se,ymax=mean+se),width=0.1)+labs(title="Bar Plot: \nMean Accuracy for Control Test Trials and Adaptive Test Trials \nin Main Experiment",size=12) +theme_bw()+theme(panel.grid.major=element_blank(),plot.title=element_text(size=12),axis.title=element_text(size=12))+ylab("Mean Accuracy")+xlab(" ") +geom_signif(comparisons=list(c("Adaptive Test Trials","Control Test Trials")),map_signif_level=TRUE,y_position=c(0.9,0.95))+ylim(0,0.98) 

accuracyscatter.main<-ggplot(subset(accuracydata,session=="s1s2"),aes(x=accuracy_adaptivetest,y=accuracy_controltest)) +geom_point() +theme_classic() +xlab("Accuracy in Adaptive Test Trials") +ylab("Accuracy in Control Test Trials") +labs(title="Scatter Plot: Accuracy in Adaptive Test Trials and Control Test Trials for Main Experiment") +geom_abline(intercept=0,slope=1,color="red")+xlim(0,1)+ylim(0,1) 

accuracyscatter.5trial<-ggplot(subset(accuracydata,session=="p1"),aes(x=accuracy_adaptivetest,y=accuracy_controltest)) +geom_point() +theme_classic() +xlab("Accuracy in Adaptive Test Trials") +ylab("Accuracy in Control Test Trials") +labs(title="Scatter Plot: Accuracy in Adaptive Test Trials and Control Test Trials for 5-Trial Adaption Experiment") +geom_abline(intercept=0,slope=1,color="red")+xlim(0,1)+ylim(0,1) 

accuracyscatter.doubleresponsetime<-ggplot(subset(accuracydata,session=="s3"),aes(x=accuracy_adaptivetest,y=accuracy_controltest)) +geom_point() +theme_classic() +xlab("Accuracy in Adaptive Test Trials") +ylab("Accuracy in Control Test Trials") +labs(title="Scatter Plot: Accuracy in Adaptive Test Trials and Control Test Trials for Double Response Time Experiment") +geom_abline(intercept=0,slope=1,color="red")+xlim(0,1)+ylim(0,1) 

#ACCURACY TESTS

sequenceaccuracy<-setNames(aggregate(data$correct, by=list(data$Sequence.,data$user),FUN=mean),c("Sequence.","user","sequenceaccuracy"))
data<-merge(data,sequenceaccuracy,by=c("Sequence.","user"))

t.test(subset(accuracydata,session=="p1")$accuracy_controltest,subset(accuracydata,session=="p1")$accuracy_adaptivetest,paired=TRUE)
t.test(subset(accuracydata,session=="p2")$accuracy_controltest,subset(accuracydata,session=="p2")$accuracy_adaptivetest,paired=TRUE)
t.test(subset(accuracydata,session=="s3")$accuracy_controltest,subset(accuracydata,session=="s3")$accuracy_adaptivetest,paired=TRUE)
t.test(subset(accuracydata,session=="s1s2")$accuracy_controltest,subset(accuracydata,session=="s1s2")$accuracy_adaptivetest,paired=TRUE)

controlgreater<-ifelse(accuracydata$accuracy_controltest>accuracydata$accuracy_adaptivetest,1,ifelse(accuracydata$accuracy_controltest<accuracydata$accuracy_adaptivetest,-1,0))
controladaptivedifference<-(accuracydata$accuracy_controltest)-(accuracydata$accuracy_adaptivetest)
accuracydata<-cbind(controlgreater,controladaptivedifference,accuracydata)
wilcox.test(subset(accuracydata,session=="p1")$controlgreater)
wilcox.test(subset(accuracydata,session=="p2")$controlgreater)
wilcox.test(subset(accuracydata,session=="s3")$controlgreater)
wilcox.test(subset(accuracydata,session=="s1s2")$controlgreater)

testdifference<-(accuracydata$accuracy_controltest)-(accuracydata$accuracy_adaptivetest)
accuracydata<-cbind(accuracydata,testdifference)
t.test(subset(accuracydata,session=="s1s2")$testdifference,subset(accuracydata,session=="s3")$testdifference)
t.test(subset(accuracydata,session=="s1s2")$testdifference,subset(accuracydata,session=="p1")$testdifference)

t.test(subset(accuracydata,session=="s1s2")$accuracy_adaptivetrial,subset(accuracydata,session=="s1s2")$accuracy_controltrial,paired=TRUE)
t.test(subset(accuracydata,session=="p1")$accuracy_adaptivetrial,subset(accuracydata,session=="p1")$accuracy_controltrial,paired=TRUE)
t.test(subset(accuracydata,session=="p2")$accuracy_adaptivetrial,subset(accuracydata,session=="p2")$accuracy_controltrial,paired=TRUE)
t.test(subset(accuracydata,session=="s3")$accuracy_adaptivetrial,subset(accuracydata,session=="s3")$accuracy_controltrial,paired=TRUE)

#CHI SQUARED & ANOVA TESTS

library("stringr")
time<-str_sub(data$Response.Time,-8,-4)
time<-as.numeric(time)

seqSD<-
  ifelse(grepl("-1",data$Trial.Type.mean.std.),1,
         ifelse(grepl("-2",data$Trial.Type.mean.std.),2,0))

seqmeancolor<-
  ifelse(grepl("3-",data$Trial.Type.mean.std.),3,
         ifelse(grepl("4-",data$Trial.Type.mean.std.),4,
                ifelse(grepl("5-",data$Trial.Type.mean.std.),5,
                       ifelse(grepl("6-",data$Trial.Type.mean.std.),6,
                              ifelse(grepl("7-",data$Trial.Type.mean.std.),7,
                                     ifelse(grepl("8-",data$Trial.Type.mean.std.),8,
                                            ifelse(grepl("9-",data$Trial.Type.mean.std.),9,
                                                   ifelse(grepl("10-",data$Trial.Type.mean.std.),10,0))))))))

color1<-
  ifelse(grepl("2 &",data$Shade),2,
         ifelse(grepl("3 &",data$Shade),3,
                ifelse(grepl("4 &",data$Shade),4,
                       ifelse(grepl("5 &",data$Shade),5,
                              ifelse(grepl("6 &",data$Shade),6,
                                     ifelse(grepl("7 &",data$Shade),7,
                                            ifelse(grepl("8 &",data$Shade),8,
                                                   ifelse(grepl("9 &",data$Shade),9,
                                                          ifelse(grepl("10 &",data$Shade),10,
                                                                 ifelse(grepl("11 &",data$Shade),11,
                                                                        ifelse(grepl("12 &",data$Shade),12,1)))))))))))

color2<-
  ifelse(grepl("& 2",data$Shade),2,
         ifelse(grepl("& 3",data$Shade),3,
                ifelse(grepl("& 4",data$Shade),4,
                       ifelse(grepl("& 5",data$Shade),5,
                              ifelse(grepl("& 6",data$Shade),6,
                                     ifelse(grepl("& 7",data$Shade),7,
                                            ifelse(grepl("& 8",data$Shade),8,
                                                   ifelse(grepl("& 9",data$Shade),9,
                                                          ifelse(grepl("& 10",data$Shade),10,
                                                                 ifelse(grepl("& 11",data$Shade),11,
                                                                        ifelse(grepl("& 12",data$Shade),12,1)))))))))))

coloravg<-(color1+color2)/2

extreme2<-ifelse(color1==1,1,ifelse(color1==2,1,ifelse(color2==1,1,ifelse(color2==2,1,ifelse(color1==11,1,ifelse(color1==12,1,ifelse(color2==11,1,ifelse(color2==12,1,0))))))))

extreme1<-ifelse(color1==1,1,ifelse(color2==1,1,ifelse(color1==12,1,ifelse(color2==12,1,0))))

data<-cbind(data,time,seqSD,seqmeancolor,color1,color2,coloravg,extreme2,extreme1)

data.noadaptivetest<-subset(data,trialtype!="adaptivetest")
data.noadaptivetest.noextreme<-subset(data.noadaptivetest,extreme2==0)

anova(lm(subset(data.noadaptivetest,session=="s1s2"|session=="s3")$correct~ subset(data.noadaptivetest,session=="s1s2"|session=="s3")$time))
anova(lm(subset(data.noadaptivetest,session=="s1s2"|session=="s3")$sequenceaccuracy~ subset(data.noadaptivetest,session=="s1s2"|session=="s3")$seqSD))
anova(lm(subset(data.noadaptivetest,session=="s1s2"|session=="s3")$correct~ subset(data.noadaptivetest,session=="s1s2"|session=="s3")$coloravg))
anova(lm(subset(data.noadaptivetest.noextreme,session=="s1s2"|session=="s3")$correct~subset(data.noadaptivetest.noextreme,session=="s1s2"|session=="s3")$coloravg))
chisq.test(subset(data.noadaptivetest,session=="s1s2"|session=="s3")$correct, subset(data.noadaptivetest,session=="s1s2"|session=="s3")$extreme2,correct=FALSE)
chisq.test(subset(data.noadaptivetest,session=="s1s2"|session=="s3")$correct, subset(data.noadaptivetest,session=="s1s2"|session=="s3")$extreme1,correct=FALSE)

anova(lm(subset(data.noadaptivetest,session=="s1s2")$correct~ subset(data.noadaptivetest,session=="s1s2")$time))
anova(lm(subset(data.noadaptivetest,session=="s1s2")$sequenceaccuracy~ subset(data.noadaptivetest,session=="s1s2")$seqSD))
anova(lm(subset(data.noadaptivetest,session=="s1s2")$correct~ subset(data.noadaptivetest,session=="s1s2")$coloravg))
anova(lm(subset(data.noadaptivetest.noextreme,session=="s1s2")$correct~ subset(data.noadaptivetest.noextreme,session=="s1s2")$coloravg))
chisq.test(subset(data.noadaptivetest,session=="s1s2")$correct, subset(data.noadaptivetest,session=="s1s2")$extreme2,correct=FALSE)
chisq.test(subset(data.noadaptivetest,session=="s1s2")$correct, subset(data.noadaptivetest,session=="s1s2")$extreme1,correct=FALSE)

anova(lm(subset(data.noadaptivetest,session=="s3")$correct~ subset(data.noadaptivetest,session=="s3")$time))
anova(lm(subset(data.noadaptivetest,session=="s3")$sequenceaccuracy~ subset(data.noadaptivetest,session=="s3")$seqSD))
anova(lm(subset(data.noadaptivetest,session=="s3")$correct~ subset(data.noadaptivetest,session=="s3")$coloravg))
anova(lm(subset(data.noadaptivetest.noextreme,session=="s3")$correct~ subset(data.noadaptivetest.noextreme,session=="s3")$coloravg))
chisq.test(subset(data.noadaptivetest,session=="s3")$correct, subset(data.noadaptivetest,session=="s3")$extreme2,correct=FALSE)
chisq.test(subset(data.noadaptivetest,session=="s3")$correct, subset(data.noadaptivetest,session=="s3")$extreme1,correct=FALSE)

#FACTORIAL ANALYSIS - TIME

data_adaptivetrial<-subset(data,trialtype=="adaptivetrial")
data_controltrial<-subset(data,trialtype=="controltrial")
data_adaptivetest<-subset(data,trialtype=="adaptivetest")
data_controltest<-subset(data,trialtype=="controltest")
data_samecolor<-subset(data,samecolor==1)
data_diffcolor<-subset(data,samecolor==0)

time_overall<-setNames(aggregate(data$time, by=list(data$user),FUN=mean),c("user","time_overall"))
time_samecolor<-setNames(aggregate(data_samecolor$time, by=list(data_samecolor$user),FUN=mean),c("user","time_samecolor"))
time_diffcolor<-setNames(aggregate(data_diffcolor$time, by=list(data_diffcolor$user),FUN=mean),c("user","time_diffcolor"))
time_adaptivetrial<-setNames(aggregate(data_adaptivetrial$time, by=list(data_adaptivetrial$user),FUN=mean),c("user","time_adaptivetrial"))
time_controltrial<-setNames(aggregate(data_controltrial$time,
                                      by=list(data_controltrial$user),FUN=mean),c("user","time_controltrial"))
time_adaptivetest<-setNames(aggregate(data_adaptivetest$time, by=list(data_adaptivetest$user),FUN=mean),c("user","time_adaptivetest"))
time_controltest<-setNames(aggregate(data_controltest$time, by=list(data_controltest$user),FUN=mean),c("user","time_controltest"))

timedata<-merge(time_overall,time_samecolor)
timedata<-merge(timedata,time_diffcolor)
timedata<-merge(timedata,time_adaptivetrial)
timedata<-merge(timedata,time_controltrial)
timedata<-merge(timedata,time_adaptivetest)
timedata <-merge(timedata,time_controltest)

session<-ifelse(grepl("s1",timedata$user),"s1s2",ifelse(grepl("s2",timedata$user),"s1s2",ifelse(grepl("s3",timedata$user),"s3",ifelse(grepl("p1",timedata$user),"p1",ifelse(grepl("p2",timedata$user),"p2",0)))))

timedata<-cbind(timedata,session)

time_overall_mean<-setNames(aggregate(timedata$time_overall, by=list(timedata$session),FUN=mean),c("session","time_overall_mean"))
time_overall_sd<-setNames(aggregate(timedata$time_overall, by=list(timedata$session),FUN=sd),c("session","time_overall_sd"))
se<-function(x) sd(x)/sqrt(length(x))
time_overall_se<-setNames(aggregate(timedata$time_overall, by=list(timedata$session),FUN=se),c("session","time_overall_se"))

time_samecolor_mean<-setNames(aggregate(timedata$time_samecolor, by=list(timedata$session),FUN=mean),c("session","time_samecolor_mean"))
time_samecolor_sd<-setNames(aggregate(timedata$time_samecolor, by=list(timedata$session),FUN=sd),c("session","time_samecolor_sd"))
time_samecolor_se<-setNames(aggregate(timedata$time_samecolor, by=list(timedata$session),FUN=se),c("session","time_samecolor_se"))

time_diffcolor_mean<-setNames(aggregate(timedata$time_diffcolor, by=list(timedata$session),FUN=mean),c("session","time_diffcolor_mean"))
time_diffcolor_sd<-setNames(aggregate(timedata$time_diffcolor, by=list(timedata$session),FUN=sd),c("session","time_diffcolor_sd"))
time_diffcolor_se<-setNames(aggregate(timedata$time_diffcolor, by=list(timedata$session),FUN=se),c("session","time_diffcolor_se"))

time_adaptivetrial_mean<-setNames(aggregate(timedata$time_adaptivetrial, by=list(timedata$session),FUN=mean),c("session","time_adaptivetrial_mean"))
time_adaptivetrial_sd<-setNames(aggregate(timedata$time_adaptivetrial, by=list(timedata$session),FUN=sd),c("session","time_adaptivetrial_sd"))
time_adaptivetrial_se<-setNames(aggregate(timedata$time_adaptivetrial, by=list(timedata$session),FUN=se),c("session","time_adaptivetrial_se"))

time_controltrial_mean<-setNames(aggregate(timedata$time_controltrial, by=list(timedata$session),FUN=mean),c("session","time_controltrial_mean"))
time_controltrial_sd<-setNames(aggregate(timedata$time_controltrial, by=list(timedata$session),FUN=sd),c("session","time_controltrial_sd"))
time_controltrial_se<-setNames(aggregate(timedata$time_controltrial, by=list(timedata$session),FUN=se),c("session","time_controltrial_se"))

time_adaptivetest_mean<-setNames(aggregate(timedata$time_adaptivetest, by=list(timedata$session),FUN=mean),c("session","time_adaptivetest_mean"))
time_adaptivetest_sd<-setNames(aggregate(timedata$time_adaptivetest, by=list(timedata$session),FUN=sd),c("session","time_adaptivetest_sd"))
time_adaptivetest_se<-setNames(aggregate(timedata$time_adaptivetest, by=list(timedata$session),FUN=se),c("session","time_adaptivetest_se"))

time_controltest_mean<-setNames(aggregate(timedata$time_controltest, by=list(timedata$session),FUN=mean),c("session","time_controltest_mean"))
time_controltest_sd<-setNames(aggregate(timedata$time_controltest, by=list(timedata$session),FUN=sd),c("session","time_controltest_sd"))
time_controltest_se<-setNames(aggregate(timedata$time_controltest, by=list(timedata$session),FUN=se),c("session","time_controltest_se"))

timebysession<-merge(time_overall_mean,time_overall_sd)
timebysession<-merge(timebysession,time_overall_se)
timebysession<-merge(timebysession,time_samecolor_mean)
timebysession<-merge(timebysession,time_samecolor_sd)
timebysession<-merge(timebysession,time_samecolor_se)
timebysession<-merge(timebysession,time_diffcolor_mean)
timebysession<-merge(timebysession,time_diffcolor_sd)
timebysession<-merge(timebysession,time_diffcolor_se)
timebysession<-merge(timebysession,time_adaptivetrial_mean)
timebysession<-merge(timebysession,time_adaptivetrial_sd)
timebysession<-merge(timebysession,time_adaptivetrial_se)
timebysession<-merge(timebysession,time_controltrial_mean)
timebysession<-merge(timebysession,time_controltrial_sd)
timebysession<-merge(timebysession,time_controltrial_se)
timebysession<-merge(timebysession,time_adaptivetest_mean)
timebysession<-merge(timebysession,time_adaptivetest_sd)
timebysession<-merge(timebysession,time_adaptivetest_se)
timebysession<-merge(timebysession,time_controltest_mean)
timebysession<-merge(timebysession,time_controltest_sd)
timebysession<-merge(timebysession,time_controltest_se)

timedatamelt<-melt(timedata)
timedatamelt<-subset(timedatamelt,variable=="time_adaptivetest"| variable=="time_controltest")

sessionname<-
  ifelse(timedatamelt$session=="p1","placebo1",
         ifelse(timedatamelt$session=="p2","placebo2",
                ifelse(timedatamelt$session=="s1s2","mainexperiment",
                       ifelse(timedatamelt$session=="s3","doubleresponsetime",0))))
timedatamelt<-cbind(timedatamelt,sessionname)
library(ggplot2)

timedensityplot<-ggplot(timedatamelt) +geom_density(aes(x=value,colour=sessionname),kernel="gaussian",adjust=0.9,show.legend=FALSE) +stat_density(aes(x=value,colour=sessionname),geom="line",position="identity",size=0) +guides(colour=guide_legend(override.aes=list(size=1))) +xlab("Response Time (sec)")+ylab("Density")+labs(title="Density Plot: \nMean Response Duration Across Experiments")+theme_classic() +scale_color_manual(values=c("orange","blue","green","red"),name="",breaks=c("mainexperiment","placebo1","placebo2","doubleresponsetime"),labels=c("Main Experiment","5-Trial Adaption Experiment","Placebo Experiment","Double Response Time")) +theme(plot.title=element_text(size=12),axis.title=element_text(size=12),legend.position=c(0.6,0.6)) +scale_x_continuous(expand=c(0,0)) +scale_y_continuous(expand=c(0,0)) 

timedatamelt<-melt(timedata)
timedatamelt<-subset(timedatamelt,variable=="time_overall")
t.test(subset(timedatamelt,session=="s1s2")$value,subset(timedatamelt,session=="p1")$value)
t.test(subset(timedatamelt,session=="s1s2")$value,subset(timedatamelt,session=="p2")$value)
t.test(subset(timedatamelt,session=="s1s2")$value,subset(timedatamelt,session=="s3")$value)
t.test(subset(timedatamelt,session=="p1")$value,subset(timedatamelt,session=="p2")$value)
t.test(subset(timedatamelt,session=="p1")$value,subset(timedatamelt,session=="s3")$value)
t.test(subset(timedatamelt,session=="p2")$value,subset(timedatamelt,session=="s3")$value)

#FACTORIAL ANALYSIS - EARNINGS

data.p1.1000<-subset(data,session=="p1"&Trial.=="1000")
data.p1.1000<-data.p1.1000[,c(1,9,10,11)]
data.p2.960<-subset(data,session=="p2"&Trial.=="960")
data.p2.960<-data.p2.960[,c(1,9,10,11)]
data.s1s2.1128<-subset(data,session=="s1s2"&Trial.=="1128")
data.s1s2.1128<-data.s1s2.1128[,c(1,9,10,11)]
data.s3.1128<-subset(data,session=="s3"&Trial.=="1128")
data.s3.1128<-data.s3.1128[,c(1,9,10,11)]

moneydata<-rbind(data.p1.1000,data.p2.960,data.s1s2.1128,data.s3.1128)
totalearned<-substr(moneydata$Accumulated.Amount,2,6)
moneydata<-cbind(moneydata,totalearned)
setwd("/Users/danielagrinblatt/Desktop/Elise/Data")
earningsbyuser<-read.csv(file("earningsbyuser.csv"),header=T,sep=",")

number_ticks<-function(n) {function(limits) pretty(limits, n)}
earningsdensityplot<-ggplot(earningsbyuser) +geom_density(aes(x=totalearned,colour=session),kernel="gaussian",adjust=0.9,show.legend=FALSE)  +stat_density(aes(x=totalearned,colour=session),geom="line",position="identity",size=0) +guides(colour=guide_legend(override.aes=list(size=1))) +xlab("Mean Earnings ($)") +ylab("Density") +ggtitle("Density Plot: \nMean Earnings Across Experiments") +theme_classic() +scale_color_manual(values=c("green","red","blue","orange"),name="",breaks=c("s1s2","p1","p2","s3"),labels=c("Main Experiment","5-Trial Adaption Experiment","Placebo Experiment","Double Response Time")) +theme(plot.title=element_text(size=12),axis.title=element_text(size=12),legend.position=c(0.3,0.8)) +scale_x_continuous(expand=c(0,0),limit=c(-60,120),breaks=number_ticks(10)) +scale_y_continuous(expand=c(0,0),limit=c(0,0.05)) 

#FACTORIAL ANALYSIS – MISSED TRIALS

misseddata<-data[,c(7,10,11)]
misseddata.p1<-subset(misseddata,session=="p1")
misseddata.p2<-subset(misseddata,session=="p2")
misseddata.s1s2<-subset(misseddata,session=="s1s2")
misseddata.s3<-subset(misseddata,session=="s3")
misseddata.p1<-setNames(aggregate(misseddata.p1$Missed, by=list(misseddata.p1$user),FUN=sum),c("user","missedtrials"))
misseddata.p2<-setNames(aggregate(misseddata.p2$Missed, by=list(misseddata.p2$user),FUN=sum),c("user","missedtrials"))
misseddata.s1s2<-setNames(aggregate(misseddata.s1s2$Missed, by=list(misseddata.s1s2$user),FUN=sum),c("user","missedtrials"))
misseddata.s3<-setNames(aggregate(misseddata.s3$Missed, by=list(misseddata.s3$user),FUN=sum),c("user","missedtrials"))
misseddata<-rbind(misseddata.p1,misseddata.p2)
misseddata<-rbind(misseddata,misseddata.s1s2)
misseddata<-rbind(misseddata,misseddata.s3)

#SEQUENCE MEAN COLOR DENSITY PLOT

sequencemeancolorhistogram.adaptive<-ggplot(subset(data,trialtype=="adaptivetrial"),aes(x=seqmeancolor,group=session)) +geom_bar(aes(y=..prop..,fill=factor(..x..)),stat="count")+scale_y_continuous(labels=scales::percent)+facet_grid(~session) +labs(title="Frequency Plot: \nSequence Mean Color in Adaptive Sequences") +theme_classic()+xlab("Sequence Mean Color")+ylab("Relative Frequency") +scale_fill_manual(values=c("gray80","gray70","gray60","gray50","gray40","gray30","gray20","gray10"))+scale_x_continuous(breaks=scales::pretty_breaks(n=8))

sequencemeancolorhistogram.control<-ggplot(subset(data,trialtype=="controltrial"),aes(x=seqmeancolor,group=session)) +geom_bar(aes(y=..prop..,fill=factor(..x..)),stat="count")+scale_y_continuous(labels=scales::percent)+facet_grid(~session) +labs(title="Frequency Plot: \nSequence Mean Color in Control Sequences") +theme_classic()+xlab("Sequence Mean Color")+ylab("Relative Frequency") +scale_fill_manual(values=c("gray80","gray70","gray60","gray50","gray40","gray30","gray20","gray10"))+scale_x_continuous(breaks=scales::pretty_breaks(n=8))

